# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the User')),
                ('date', models.DateTimeField(verbose_name='Date Registered')),
                ('password', models.CharField(max_length=100, verbose_name='Hash of Email Registration Password')),
            ],
        ),
    ]
